package com.trungkien.cleanvehicle

import android.Manifest
import android.content.pm.PackageManager
import android.graphics.Color
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import android.widget.FrameLayout
import android.widget.TextView
import androidx.activity.ComponentActivity
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.AspectRatio
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.ImageProxy
import androidx.camera.core.Preview
import androidx.camera.core.resolutionselector.AspectRatioStrategy
import androidx.camera.core.resolutionselector.ResolutionSelector
import androidx.camera.core.resolutionselector.ResolutionStrategy
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.core.content.ContextCompat
import java.io.File
import java.util.Locale
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.math.roundToInt

class MainActivity:ComponentActivity(){
    private lateinit var preview:PreviewView; private lateinit var overlay:SpcVideoOverlay; private lateinit var status:TextView; private lateinit var settings:TextView; private lateinit var blackout:TextView; private var savedBrightness:Float?=null
    private val analyzer=Executors.newSingleThreadExecutor();private val modelExec=Executors.newSingleThreadExecutor();private val scExec=Executors.newSingleThreadExecutor();private val main=Handler(Looper.getMainLooper());private val scBusy=AtomicBoolean(false)
    private lateinit var license:AdasLicenseManager;private lateinit var speed:AdasSpeedProvider;private lateinit var calibrator:AdasAutoCalibrator;private lateinit var voice:GoogleAdasVoice;private lateinit var store:AdasFeatureStore;private lateinit var virtual:AdasVirtualCamera;private lateinit var thermal:AdasThermalMonitor
    @Volatile private var features=AdasFeatureConfig.spcCore();private var engine=SupercomboAdasEngine();private val beeper=AdasBeeper()
    @Volatile private var laneDetector:UfldLaneDetector?=null;@Volatile private var scDetector:SupercomboDetector?=null;@Volatile private var latest:SupercomboResult?=null;@Volatile private var snapshot=AdasSnapshot()
    @Volatile private var laneMs=0f;@Volatile private var scMs=0f;@Volatile private var laneCount=0L;@Volatile private var scCount=0L;@Volatile private var pairMs=0L
    private var prevScTs=0L;private var frameCount=0L;private var prevHmw=false;private var prevLdw=false;private var calLocked=false;private var fps=0f;private var fpsFrames=0L;private var fpsStart=SystemClock.elapsedRealtime()
    private val permissions=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){r->val ok=r[Manifest.permission.CAMERA]==true||ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED;if(!ok){status.text="CẦN QUYỀN CAMERA";return@registerForActivityResult};speed.start();loadModels()}

    override fun onCreate(b:Bundle?){super.onCreate(b);license=AdasLicenseManager(this);if(!license.hasAccess()){gate();return};store=AdasFeatureStore(this);features=store.load().copy(yolox=false,supercombo=true,fusionSmartLead=false,distanceMode=LeadDistanceMode.SUPERCOMBO);speed=AdasSpeedProvider(this);calibrator=AdasAutoCalibrator(this);calLocked=calibrator.geometry.locked;virtual=AdasVirtualCamera(this);thermal=AdasThermalMonitor(this);voice=GoogleAdasVoice(this);window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);@Suppress("DEPRECATION") run{window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_FULLSCREEN or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY};ui();license.startTrialClock();request();main.post(heartbeat)}
    private fun gate(){@Suppress("DEPRECATION") run{window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_FULLSCREEN or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY};setContentView(AdasLicenseGateView(this,license){recreate()})}
    private fun request(){val c=ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED;val l=ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;if(c){if(l)speed.start();loadModels()}else permissions.launch(arrayOf(Manifest.permission.CAMERA,Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))}
    private fun ui(){val root=FrameLayout(this).apply{setBackgroundColor(Color.BLACK)};preview=PreviewView(this).apply{implementationMode=PreviewView.ImplementationMode.PERFORMANCE;scaleType=PreviewView.ScaleType.FILL_CENTER};overlay=SpcVideoOverlay(this);status=TextView(this).apply{setTextColor(Color.WHITE);setBackgroundColor(Color.argb(105,0,0,0));textSize=11f;setPadding(12,7,12,7);text="TrungKien ADAS V4.2.1 • SPC CORE"};settings=TextView(this).apply{setTextColor(Color.WHITE);setBackgroundColor(Color.argb(205,0,108,92));textSize=14f;setPadding(18,12,18,12);text="⚙ CÀI ĐẶT";setOnClickListener{showSettings()}};blackout=TextView(this).apply{setBackgroundColor(Color.BLACK);setTextColor(Color.rgb(35,35,35));textSize=12f;gravity=Gravity.CENTER;text="MÀN HÌNH ĐEN • CHẠM ĐỂ BẬT";visibility=View.GONE;setOnClickListener{exitCoolingScreen()}};root.addView(preview,FrameLayout.LayoutParams(-1,-1));root.addView(overlay,FrameLayout.LayoutParams(-1,-1));root.addView(status,FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM or Gravity.START).apply{bottomMargin=10;marginStart=10});root.addView(settings,FrameLayout.LayoutParams(-2,-2,Gravity.TOP or Gravity.END).apply{topMargin=12;marginEnd=12});root.addView(blackout,FrameLayout.LayoutParams(-1,-1));setContentView(root)}
    private fun showSettings(){license.stopTrialClock();V42SettingsDialog(this,license,voice,features,{metrics()},{applyFeatures(it)},{recreate()},{enterCoolingScreen()}).apply{setOnDismissListener{if(!license.isLicensed()&&license.hasAccess())license.startTrialClock()};show()}} private fun enterCoolingScreen(){savedBrightness=window.attributes.screenBrightness;val a=window.attributes;a.screenBrightness=0.01f;window.attributes=a;blackout.visibility=View.VISIBLE;blackout.bringToFront()} private fun exitCoolingScreen(){val a=window.attributes;a.screenBrightness=savedBrightness?:WindowManager.LayoutParams.BRIGHTNESS_OVERRIDE_NONE;window.attributes=a;blackout.visibility=View.GONE}
    private fun applyFeatures(v:AdasFeatureConfig){features=v.copy(yolox=false,supercombo=true,fusionSmartLead=false,distanceMode=LeadDistanceMode.SUPERCOMBO);store.save(features);engine=SupercomboAdasEngine();prevHmw=false;prevLdw=false;beeper.updateFcwLevel(0)}

    private fun loadModels(){status.text="V4.2.1 • ĐANG NẠP SPC...";modelExec.execute{runCatching{laneDetector=UfldLaneDetector(copyLane());scDetector=SupercomboDetector(copySc())}.onSuccess{runOnUiThread{status.text="V4.2.1 • SPC READY";startCamera()}}.onFailure{e->runOnUiThread{status.text="LỖI MODEL • ${e.javaClass.simpleName}: ${e.message}"}}}}
    private fun copyLane():File{val f=File(filesDir,"ufld_culane_trungkien_adas.onnx");if(f.exists()&&f.length()==178_076_232L)return f;assets.open("ufld_culane.onnx").use{i->f.outputStream().use{o->i.copyTo(o,512*1024)}};require(f.length()==178_076_232L);return f}
    private fun copySc():File{val f=File(filesDir,"supercombo_spc_core.onnx");if(f.exists()&&f.length()==SupercomboDetector.MODEL_FILE_SIZE)return f;assets.open("supercombo.onnx").use{i->f.outputStream().use{o->i.copyTo(o,512*1024)}};require(f.length()==SupercomboDetector.MODEL_FILE_SIZE);return f}
    private fun startCamera(){val future=ProcessCameraProvider.getInstance(this);future.addListener({runCatching{val p=future.get();val pv=Preview.Builder().setTargetAspectRatio(AspectRatio.RATIO_16_9).build().also{it.surfaceProvider=preview.surfaceProvider};val rs=ResolutionSelector.Builder().setAspectRatioStrategy(AspectRatioStrategy(AspectRatio.RATIO_16_9,AspectRatioStrategy.FALLBACK_RULE_AUTO)).setResolutionStrategy(ResolutionStrategy(android.util.Size(1280,720),ResolutionStrategy.FALLBACK_RULE_CLOSEST_LOWER_THEN_HIGHER)).build();val a=ImageAnalysis.Builder().setResolutionSelector(rs).setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888).setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();a.setAnalyzer(analyzer,::analyze);p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pv,a)}.onFailure{e->status.text="LỖI CAMERA • ${e.message}"}},ContextCompat.getMainExecutor(this))}

    private fun analyze(image:ImageProxy){val lane=laneDetector;val sc=scDetector;if(lane==null||sc==null){image.close();return};try{frameCount++;tickFps();val dims=dims(image);val helperStride=thermal.ufldHelperStride(features.thermalProtection);val runU=!virtual.state.ready&&frameCount%2L==0L||(virtual.state.ready&&features.ufld&&frameCount%helperStride==0L);if(runU){val lr=lane.detect(image);laneMs=lr.inferenceMs;laneCount++;calibrator.observe(lr);val vs=virtual.observe(calibrator.geometry,dims.first,dims.second,speed.speedKph);sc.updateVirtualCamera(vs);val lock=calibrator.geometry.locked;if(!calLocked&&lock){calLocked=true;voice.calibrationSuccess();runOnUiThread{overlay.showCalibrationSuccess()}}};launchSc(image)}catch(e:Throwable){beeper.updateFcwLevel(0);runOnUiThread{status.text="SPC ERROR • ${e.javaClass.simpleName}: ${e.message}"}}finally{image.close()}}
    private fun launchSc(image:ImageProxy){val d=scDetector?:return;val stride=thermal.supercomboStride(features.thermalProtection);if(frameCount%stride!=0L||!scBusy.compareAndSet(false,true))return;val prep=runCatching{d.prepare(image)}.getOrElse{scBusy.set(false);return};if(prep==null){scBusy.set(false);return};scExec.execute{try{val r=d.infer(prep);val old=prevScTs;prevScTs=r.timestampMs;if(old>0)pairMs=(r.timestampMs-old).coerceIn(0,9999);latest=r;scMs=r.inferenceMs;scCount++;val scLane=r.laneGeometry.takeIf{features.supercomboLanePath&&it.valid&&it.confidence>=0.42f};val ufLane=calibrator.geometry.takeIf{features.ufld&&it.valid};val lane=scLane?:ufLane?:AdasLaneGeometry();if(!virtual.state.ready&&lane.valid){virtual.observe(lane,r.sourceWidth,r.sourceHeight,speed.speedKph);d.updateVirtualCamera(virtual.state)};val raw=engine.update(if(features.supercomboLead)r else r.copy(leadHint=null),lane,calibrator.hoodTopNorm(),speed.speedKph,SystemClock.elapsedRealtime());val s=mask(raw);snapshot=s;val th=thermal.sample();runOnUiThread{warnings(s);overlay.update(r,s,virtual.state,th,fps,pairMs,features.technicalInfo)}}catch(e:Throwable){runOnUiThread{if(features.technicalInfo)status.text="SC ERROR • ${e.javaClass.simpleName}: ${e.message}"}}finally{scBusy.set(false)}}}
    private fun dims(i:ImageProxy):Pair<Int,Int>{val r=((i.imageInfo.rotationDegrees%360)+360)%360;return if(r==90||r==270)i.height to i.width else i.width to i.height}
    private fun tickFps(){fpsFrames++;val now=SystemClock.elapsedRealtime();val dt=now-fpsStart;if(dt>=1000){fps=fpsFrames*1000f/dt;fpsFrames=0;fpsStart=now}}
    private fun fresh():SupercomboResult?{val r=latest?:return null;return if(SystemClock.elapsedRealtime()-r.timestampMs<=2400L)r else null}
    private fun mask(s:AdasSnapshot):AdasSnapshot{val w=s.warnings;return s.copy(warnings=w.copy(fcwLevel=if(features.fcwHmw)w.fcwLevel else 0,hmwWarning=features.fcwHmw&&w.hmwWarning,voiceFcwEvent=features.fcwHmw&&w.voiceFcwEvent,ldwWarning=features.ldwTlc&&w.ldwWarning,ldwDirection=if(features.ldwTlc)w.ldwDirection else 0,voiceLdwEvent=features.ldwTlc&&w.voiceLdwEvent))}
    private fun warnings(s:AdasSnapshot){if(features.fcwHmw)beeper.updateFcwLevel(s.warnings.fcwLevel)else beeper.updateFcwLevel(0);if(s.warnings.leadMovedEvent){beeper.leadMovedCue();voice.leadMoved()};if(features.fcwHmw&&s.warnings.voiceFcwEvent)voice.collisionRisk();if(features.ldwTlc&&s.warnings.ldwWarning&&!prevLdw)beeper.laneCue();if(features.ldwTlc&&s.warnings.voiceLdwEvent)voice.laneDeparture();if(features.fcwHmw&&s.warnings.hmwWarning&&!prevHmw&&s.warnings.fcwLevel==0){beeper.headwayCue();voice.headwayTooClose()};prevHmw=s.warnings.hmwWarning;prevLdw=s.warnings.ldwWarning}
    private fun metrics():String{val r=fresh();val h=r?.leadHint;val v=virtual.state;val th=thermal.sample();return buildString{append("CORE: SPC ONLY\nYOLO: REMOVED / NO MODEL / NO INFERENCE\n");append("SPC: ${scMs.roundToInt()} ms • pair $pairMs ms • n=$scCount\n");append("LEAD: ${h?.distanceMeters?.let{String.format(Locale.US,"%.1f m",it)}?:"--"} • CONF ${h?.probability?.let{"${(it*100).roundToInt()}%"}?:"--"}\n");append("OUT: ${snapshot.lead?.distanceMeters?.let{String.format(Locale.US,"%.1f m",it)}?:"--"} • TTC ${snapshot.ttcSeconds?.let{String.format(Locale.US,"%.1f s",it)}?:"--"}\n");append("feat ${v.featureSamples}/${v.featureRequired} • CAL ${(v.calibrationQuality*100).roundToInt()}%\n");append("pitch ${String.format(Locale.US,"%.2f",v.pitchDeg)} • yaw ${String.format(Locale.US,"%.2f",v.yawDeg)}\n");append("fPx ${v.focalPx.toInt()} r ${String.format(Locale.US,"%.3f",v.fxRatio)} • ${v.intrinsicSource}\n");append("UFLD helper ${laneMs.roundToInt()}ms • thermal ${th.label}")}}
    private val heartbeat=object:Runnable{override fun run(){license.consumeTrialNow();if(!license.hasAccess()){beeper.updateFcwLevel(0);recreate();return};status.text=if(features.technicalInfo)"V4.2.1 • SPC VIDEO • ${String.format(Locale.US,"%.1f",fps)} FPS • ${scMs.roundToInt()}ms" else "V4.2.1 • SPC CORE • ${licenseText()} • ${if(fresh()!=null)"SPC LIVE" else "SPC WAIT"}";main.postDelayed(this,1000)}}
    private fun licenseText():String{if(license.isLicensed())return license.licenseSummary();val s=(license.remainingTrialMs()+999)/1000;return "DÙNG THỬ %02d:%02d".format(Locale.US,s/60,s%60)}
    override fun onResume(){super.onResume();if(::license.isInitialized&&license.hasAccess())license.startTrialClock()};override fun onPause(){if(::license.isInitialized)license.stopTrialClock();super.onPause()};override fun onDestroy(){if(::license.isInitialized)license.stopTrialClock();main.removeCallbacks(heartbeat);beeper.updateFcwLevel(0);beeper.close();if(::voice.isInitialized)voice.close();if(::speed.isInitialized)speed.stop();laneDetector?.close();scDetector?.close();analyzer.shutdownNow();modelExec.shutdownNow();scExec.shutdownNow();super.onDestroy()}
}
